<HTML>

<Head>
<Meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
<Title>Электронный ресурс по учебной дисциплине ОСАПр. Заочное</Title>
<Meta Name="Description" http-equiv="description" Content="Электронный ресурс по учебной дисциплине ОСАПр. Заочное">
<Link Rel="stylesheet" Type="text/css" Href="../Оболочка/acad.css">

<Script Language="JavaScript">
	function mOver(num) {
		if (document.images) {
			document.images['link'+num].src=eval('active'+num+'.src');
		}
	}
	function mOut(num) {
		if (document.images) {
			document.images['link'+num].src=eval('normal'+num+'.src');
		}
	}
</Script>

<Script Type="text/javascript" Src="../Оболочка/jquery.pack.js"></Script>

<Script Type="text/javascript">
var hidePostImg =	false;

function initPost(context)
{
	initSpoilers(context);
}
function initPostImages(context)
{
	if (hidePostImg) return;
	var $in_spoilers = $('div.sp-body var.postImg', context);
	$('var.postImg', context).not($in_spoilers).each(function(){
		var $v = $(this);
		var src = $v.attr('title');
		var $img = $('<img src="'+ src +'" class="'+ $v.attr('className') +'" alt="pic" />');
		$img = fixPostImage($img);
		var maxW = ($v.hasClass('postImgAligned')) ? postImgAligned_MaxWidth : postImg_MaxWidth;
		$img.bind('click', function(){ return imgFit(this, maxW); });
		if (user.opt_js.i_aft_l) {
			$('#preload').append($img);
			$v.html(loading_icon);
			if ($.browser.msie) {
				$v.after('<wbr>');
			}
			$img.one('load', function(){
				imgFit(this, maxW);
				$v.empty().append(this);
			});
		}
		else {
			$img.one('load', function(){ imgFit(this, maxW) });
			$v.empty().append($img);
			if ($.browser.msie) {
				$v.after('<wbr>');
			}
		}
	});
}
function initSpoilers(context)
{
	$('div.sp-body', context).each(function(){
		var $sp_body = $(this);
		var name = $.trim(this.title);
		this.title = '';
		var $sp_head = $('<div class="sp-head folded clickable">'+ name +'</Div>');
		$sp_head.insertBefore($sp_body).click(function(e){
			if (!$sp_body.hasClass('inited')) {
				initPostImages($sp_body);
				var $sp_fold_btn = $('<div class="sp-fold clickable"></Div>').click(function(){
					$.scrollTo($sp_head, { duration:200, axis:'y', offset:-200 });
					$sp_head.click().animate({opacity: 0.1}, 500).animate({opacity: 1}, 700);
				});
				$sp_body.prepend('<div class="clear"></Div>').append('<div class="clear"></Div>').append($sp_fold_btn).addClass('inited');
			}
			if (e.shiftKey) {
				e.stopPropagation();
				e.shiftKey = false;
				var fold = $(this).hasClass('unfolded');
				$('div.sp-head', $($sp_body.parents('td')[0])).filter( function(){ return $(this).hasClass('unfolded') ? fold : !fold } ).click();
			}
			else {
				$(this).toggleClass('unfolded');
				$sp_body.slideToggle('fast');
			}
		});
	});
}
$(function(){
	$('div.post_body, div.signature').each(function(){ initPost( $(this) ) });
});
</Script>
</Head>

<Body Bgcolor=#E6E6E6 TopMargin=1 LeftMargin=1 MarginWidth=0 MarginHeight=0>
<Div Class=max>
<Script Language="JavaScript">
if (document.images) {
	normal1=new Image(190,29);normal1.src="../Оболочка/images/01a.gif";
	active1=new Image(190,29);active1.src="../Оболочка/images/01p.gif";
	normal2=new Image(190,29);normal2.src="../Оболочка/images/02a.gif";
	active2=new Image(190,29);active2.src="../Оболочка/images/02p.gif";
	normal3=new Image(190,29);normal3.src="../Оболочка/images/03a.gif";
	active3=new Image(190,29);active3.src="../Оболочка/images/03p.gif";
	normal5=new Image(190,29);normal5.src="../Оболочка/images/05a.gif";
	active5=new Image(190,29);active5.src="../Оболочка/images/05p.gif";
	normal6=new Image(159,46);normal6.src="../Оболочка/images/06a.gif";
	active6=new Image(159,46);active6.src="../Оболочка/images/06p.gif";
	normal7=new Image(159,54);normal7.src="../Оболочка/images/07a.gif";
	active7=new Image(159,55);active7.src="../Оболочка/images/07p.gif";
}
</Script>

<A Name="Top"></A>
<Table Border=0 Width=100% CellSpacing=0 CellPadding=0>
<Tr>
 <Td BackGround=../Оболочка/images/bg01.gif Width=190 Height=91>&nbsp;</Td>
 <Td RowSpan=2 BackGround=../Оболочка/images/bg02.gif Height=120 Valign=Bottom>
<Table BackGround=../Оболочка/images/raspor.gif Border=0 CellSpacing=0 CellPadding=0>
 <Tr>
  <Td Width=140></Td>
  <Td Valign=top Height=63><P Class=h6>Задания на контрольную работу</P></Td>
 </Tr>
</Table>

</Td></Tr>
<Tr>
  <Td BackGround=../Оболочка/images/bg03.gif>
    <A Href=../Программа/!rabprog.html onMouseOver="mOver(1)" onMouseOut="mOut(1)"><Img Src=../Оболочка/images/01a.gif Border=0 Width=190 Height=29 Alt="Рабочая программа" name="link1"></A><Br>
 </Td>
</Tr>
<Tr>
 <Td Height=100% RowSpan="2" Valign=Top BackGround=../Оболочка/images/bg00.gif>

<Table Border=0 CellSpacing=0 CellPadding=0>
<Tr><Td BackGround=../Оболочка/images/bg03.gif Valign=Top>
  <A Href=../Теория/!lekcii.html onMouseOver="mOver(2)" onMouseOut="mOut(2)"><Img Src=../Оболочка/images/02a.gif Width=190 Height=29 Border=0 Alt="Лекции" name="link2"></A><Br>
 </Td>
</Tr>
<Tr><Td BackGround=../Оболочка/images/bg03.gif Width=190 Valign=Top>
 <A Href=../Практика/!zadanie.html onMouseOver="mOver(3)" onMouseOut="mOut(3)"><Img Src=../Оболочка/images/03a.gif Width=190 Height=29 Border=0 Alt="Лабораторные работы" name="link3"></A><Br>
 <Img Src=../Оболочка/images/04p.gif Width=190 Height=29 Border=0 Alt="Заочное"><Br>
 <A Href=../Контроль_знаний/!samocontrol.html onMouseOver="mOver(5)" onMouseOut="mOut(5)"><Img Src=../Оболочка/images/05a.gif Width=190 Height=29 Border=0 Alt="Самоконтроль" name="link5"></A><Br>
 <Img Src=../Оболочка/images/bg08.gif Width=190 Height=13><Br>
</Table></Td>
 
 <Td Valign=Сenter>
 <Br><Br>
 

<Table Valign="left"><Tr align="left"><Td>
<Ul>
  <Dt><A Class=m Href="../Практика/!lisp.html">Теоретические сведения</A></Dt>
</Ul>
</Td></Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right">
<Br>

<P><B>Цель работы:</B> Написать программу на языке AutoLISP, работающую в среде AutoCAD. Номер варианта - по номеру студента в списке.</P>

<Hr Width="90%" Color="#7685C6" Align="Right">
<Br>

<P Class=h6>682471</P>

<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 1" Style='display: none'></a>

<P>Создание поверхностей вращения (команда AutoCAD revsurf) на основе данных, полученных из файла. В файле содержится информация в формате диалога
опций при ручном построении полилинии (относительные координаты вершин и опции типа сегментов между вершинами), которая может состоять из отрезков и
дуг. Диалог с пользователем - без использования оконного интерфейса через командную строку. Программа должна обеспечивать:</P>

<Ul>
 <Li>выбор цвета поверхности через стандартное меню AutoCAD (acad_colordlg);</Li>
 <Li>выбор файла с данными об образующей полилинии через стандартное меню AutoCAD (getfiled);</Li>
 <Li>задание точки вставки центра основания поверхности указанием на экране координат с помощью мыши, при котором в командной строке должны
  выводиться указанные координаты <I>X</I>, <I>Y</I> с возможности коррекции значений через повторный ввод;</Li>
 <Li>возможность задания количества граней поверхности (переменная AutoCAD surftab1) и угол вращения полилинии в полях редактирования EditBox.</Li>
</Ul>

<P>Точка вставки задаёт местоположение поверхности. Ось вращения должна быть параллельна оси <I>OY</I>.</P>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 2" Style='display: none'></a>

<P>Создание поверхностей на базе четырёх образующих полилиний (команда AutoCAD edgesurf). В файле содержится информация в формате диалога
опций при ручном построении четырёх полилиний (относительные координаты вершин и опции типа сегментов между вершинами), которые могут состоять из
отрезков и дуг. Четыре полилинии, должны быть соединены друг с другом в началах и концах. Диалог с пользователем - без использования оконного
интерфейса через командную строку. Программа должна обеспечивать:</P>

<Ul>
 <Li>выбор цвета поверхности через стандартное меню AutoCAD (acad_colordlg);</Li>
 <Li>выбор файла с данными об образующей полилинии через стандартное меню AutoCAD (getfiled);</Li>
 <Li>задание точки вставки поверхности указанием на экране координат с помощью мыши, при котором в командной строке должны
  выводиться указанные координаты <I>X</I>, <I>Y</I> с возможности коррекции значений через повторный ввод;</Li>
 <Li>возможность задания количества лоскутов разбиения поверхности (переменные AutoCAD surftab1, surftab2).</Li>
</Ul>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 3" Style='display: none'></a>
<Table><Tr><Td>

<P>Отрисовка схемных изображений транзисторов. Программа в командной строке должна запрашивать выбор типа транзистора (P-N-P, N-P-N, N-канальный
полевой, P-канальный полевой); выбор цвета радиоэлемента через стандартное меню AutoCAD; возможность указать точку на графическом экране в
интерактивном режиме с отображением указанных координат <i>X</i>, <i>Y</i> в командной строке и возможности коррекции значений в них; возможность
указания ориентации элементов (без поворота, поворот на 90, поворот на 180, поворот на 270).</P>
</Td><Td>

<P Class=c>Примерный вид изображений:</P>
&nbsp;&nbsp;<Img Src=4_03_z.png></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 4" Style='display: none'></a>
<Table><Tr><Td>

<P>Отрисовка круговых массивов примитивов (треугольников, квадратов, пятиугольников и шестиугольников). Размеры и координаты центра исходного
примитива определяются в дополнительном диалоговом окне, вызываемом нажатием кнопки "Размеры примитива". Оба диалоговых окна должны быть описаны в
одном файле. Программа должна обеспечивать:</P>

<Ul>
 <Li>выбор цвета многоугольника через стандартное меню AutoCAD;</Li>
 <Li>задание точки вставки центра массива указанием на экране координат с помощью мыши, при котором диалоговое окно временно закрывается, давая
  пользователю возможность указать точку на графическом экране в интерактивном режиме, после чего диалоговое окно снова должно появиться на экране с
  отображением указанных координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox для возможности в коррекции значений в них;</Li>
 <Li>задание точки вставки центра массива указанием координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox в диалоговом
  окне;</Li>
 <Li>возможность задания радиуса описанной окружности в поле редактирования EditBox в формате числа с плавающей точкой.</Li>
</Ul>

<P>После построения массива выбранного цвета, каждый примитив в этом массиве должен быть перекрашен в цвет на единицу больше предыдущего (имеется
ввиду цвет образующей примитив линии).</P>

<P>Примечание. Базовый примитив строится при выполнении команды polygon, а массивы примитивов отрисовываются при выполнении команды AutoCAD array.
Для перезакраски примитивов массива их необходимо выбрать (ssget) и в графической базе данных чертежа изменить подсписки с DXF-кодом 62.</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=4_04_z.png></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 5" Style='display: none'></a>
<Table><Tr><Td>

<P>Построение многоугольников. Диалоговое окно должно обеспечивать выбор многоугольника с количеством углов от пяти до восьми с помощью выпадающего
меню, а более восьми – с помощью EditBox. Программа должна обеспечивать:</P>

<Ul>
 <Li>при выборе из выпадающего меню количества сторон, в соответствующем окне редактирования EditBox должно отображаться количество углов выбранного
  многоугольника;</Li>
 <Li>выбор цвета многоугольника через стандартное меню AutoCAD;</Li>
 <Li>задание точки вставки центра многоугольника указанием на экране координат с помощью мыши, при котором диалоговое окно временно закрывается,
  давая пользователю возможность указать точку на графическом экране в интерактивном режиме, после чего диалоговое окно снова должно появиться на
  экране с отображением указанных координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox для возможности в коррекции значений в
  них;</Li>
 <Li>задание точки вставки многоугольника указанием координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox в диалоговом
  окне;</Li>
 <Li>возможность задания радиуса описанной окружности в поле редактирования EditBox в формате действительного числа (тип real);</Li>
 <Li>при выборе количества углов менее трёх и более 255 (ограничения команды AutoCAD polygon) должно выдаваться сообщение об ошибке.</Li>
</Ul>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=4_05_z.png></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 6" Style='display: none'></a>
<P>Отрисовка рамки, штампа и спецификации. Диалог с пользователем - из командной строки. Программа должна обеспечивать:</P>

<Ul>
 <Li>выбор элемента для отрисовки, - рамки, штампа или спецификации;</Li>
 <Li>выбор цвета через стандартное меню AutoCAD (acad_colordlg);</Li>
 <Li>выбор слоя из существующих на текущем чертеже (программа должна вывести в командную строку список слоёв);</Li>
 <Li>задание точки вставки левого нижнего угла элементов отрисовки указанием на экране координат с помощью мыши, при котором в командной строке
  должны выводиться указанные координаты <I>X</I>, <I>Y</I> с возможности коррекции значений через повторный ввод;</Li>
 <Li>выбор формата листа (A0, A1, A2, A3). Функция должна быть активизирована только в случае выбора черчения рамки;</Li>
 <Li>заполнение полей штампа автоматически по данным полученным из предварительно созданного файла произвольного формата.</Li>
</Ul>

<P Class=c>Вид стандартного диалогового окна выбора файла:<Br>&nbsp;&nbsp;<Img Src=../Практика/images/open_file.png></P>

<Br>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 7" Style='display: none'></a>

<P>Извлечение данных о примитивах чертежа. Путём доступа к графической базе данных чертежа получить информацию (имя слоя, номер цвета, тип линии,
координаты вершин и радиус) о примитивах: отрезках, полилиниях, окружностях. Записать полученную информацию в заданный пользователем файл. Он должен
иметь для каждого типа примитва соответствующую секцию ([LINE] [POLYLINE] [CIRCLE]). Если примитив имеет цвет "ПоСлою" (ByLayer) или слой по
умолчанию, то эта информация также должна быть отражена в выходном файле. Выбор типа примитива о которых сохраняются данные - из командной строки.
Имени файла - через стандартное окно (getfiled).</P>

<P Class=c>Вид стандартного диалогового окна выбора файла:<Br>&nbsp;&nbsp;<Img Src=../Практика/images/open_file.png></P>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 8" Style='display: none'></a>
<Table><Tr><Td>

<P>Создание октантного дерева. В командной строке программа запрашивает ввод уровня разбиения (целое число) и возможность выбора многоугольника
(entsel), для которого будет строиться октантное дерево. Октантное дерево – это структура данных, которая представляет собой плоское тело в виде рекурсивного подразделения
двухмерного пространства на прямоугольные блоки (в нашей задаче квадраты).</P>

<P>Процедура построения октантного дерева. Сначала создаётся квадрат, в который многоугольник помещается целиком. Для этого находится максимальные и
минимальные координаты по Х и по Y. Далее находится сторона квадрата и его центр. Этот квадрат называется корневым октантом. Затем корневой октант
делится на 4 октанта, после чего анализируется их положение по отношению к многоугольнику. Если октант находится полностью внутри многоугольника, он
считается «чёрным»; если снаружи – «белым». Если же октант частично лежит внутри многоугольника, а частично – снаружи, то он считается «серым» и
делится на четыре октанта меньшего размера. Чёрные и белые октанты дальше не делятся. Процедура продолжается до тех пор, пока не будет достигнут
заданный уровень разбиения. «Цвет» определяется следующим образом: проверяется, пересекаются ли стороны октанта со сторонами многоугольника (с
помощью функции AutoLisp inters). Если стороны октанта пересекаются со сторонами многоугольника, то октант считается «серым». Иначе октант лежит
внутри либо снаружи многоугольника. Чтобы определить его «цвет» подсчитывается количество пересечений отрезка лежащего между центром октанта и одной
из вершин корневого октанта со сторонами многоугольника. Если количество пересечений чётное или ноль, то квадрат лежит снаружи многоугольника и
считается «белым». Иначе если количество пересечений нечётное, то он лежит внутри многоугольника и считается «чёрным». На чертеже рисуются только
октанты внутри треугольника</P>
</Ul>
</Td>
<Td><P Class=c>Процесс создания октодерева:<Br> <Img Src=../Практика/images/4_08.gif></P></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 9" Style='display: none'></a>

<P>Отрисовка полилиний по данным, полученным из предварительно созданного файла в произвольном формате. Диалог с пользователем - через командную строку.
Предусмотреть функцию сглаживания полилинии и возможность её замкнуть. Программа должна обеспечивать:</P>

<Ul>
 <Li>выбор цвета полилинии через стандартное меню AutoCAD с отображением его в диалоговом окне;</Li>
 <Li>задание точки вставки начала полилинии указанием на экране координат с помощью мыши, при котором в командной строке должны выводиться указанные
  координаты <I>X</I>, <I>Y</I> с возможности коррекции значений через повторный ввод;</Li>
  <Li>возможность выбора файла с помощью стандартного диалогового окна.</Li>
</Ul>

<P Class=c>Вид стандартного диалогового окна выбора файла:<Br>&nbsp;&nbsp;<Img Src=../Практика/images/open_file.png></P>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 10" Style='display: none'></a>

<P>Построение зубчатого колеса. Диалог с пользователем - через командную строку. Программа должна обеспечивать:</P>

<Ul>
 <Li>выбор вида зубцов (треугольные либо прямоугольные);</Li>
 <Li>задание внутреннего и внешнего радиуса колеса, длины стороны зубца;</Li>
 <Li>число зубцов вычисляется на основании внешнего радиуса колеса и длины стороны зубца;</Li>
 <Li>выбор цвета через стандартное меню AutoCAD с отображением его в диалоговом окне;</Li>
 <Li>задание точки вставки центра зубчатого колеса указанием на экране координат с помощью мыши, при котором в командной строке должны выводиться
  указанные координаты <I>X</I>, <I>Y</I> с возможности коррекции значений через повторный ввод.</Li>
</Ul>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 11" Style='display: none'></a>
<Table><Tr><Td>

<P>Отрисовка схемных изображений полевых транзисторов. Программа в командной строке должна запрашивать выбор типа транзистора (N-канальный,
P-канальный, МДП-n-канальный, и т.д.); выбор цвета радиоэлемента через стандартное меню AutoCAD; возможность указать точку на графическом экране в
интерактивном режиме с отображением указанных координат <i>X</i>, <i>Y</i> в командной строке и возможности коррекции значений в них; возможность
указания ориентации элементов (без поворота, поворот на 90, поворот на 180, поворот на 270).</P>
</Td><Td>

<P Class=c>Примерный вид изображений:</P>
&nbsp;&nbsp;<Img Src=4_11_z.png></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>


<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 12" Style='display: none'></a>

<P>Извлечение данных о примитивах чертежа. Путём доступа к графической базе данных чертежа получить информацию (имя слоя, номер цвета, тип линии,
координаты вершин и радиус) о примитивах: точках, полилиниях, сплайнах. Записать полученную информацию в заданный пользователем файл. Если примитив
имеет цвет "ПоСлою" (ByLayer) или слой по умолчанию, то эта информация также должна быть отражена в выходном файле. Выбор типа примитива о которых
сохраняются данные и имени файла - из командной строки.</P>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 13" Style='display: none'></a>

<P>Отрисовка винтов. Программа должна обеспечивать диалог с пользователем из командной строки со следующими функциями:</P>

<Ul>
 <Li>выбор типа винта (с круглой, плоской, потайной головкой и болта);</Li>
 <Li>возможность задания диаметра и длины винта, ширины и высоты головки, длину резьбы;</Li>
 <Li>выбор цвета винта через стандартное меню AutoCAD;</Li>
 <Li>задание точки вставки винта указанием на экране координат с помощью мыши, при котором в командной строке должны выводиться указанные координаты
  <I>X</I>, <I>Y</I> с возможности коррекции значений через повторный ввод.</Li>
</Ul>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 14" Style='display: none'></a>
<Table><Tr><Td>

<P>Отрисовка схемных изображений диодов. Программа в командной строке должна запрашивать выбор типа диода (выпрямительный, стабилитрон, диод Шоттки,
тунельный, варикап); выбор цвета радиоэлемента через стандартное меню AutoCAD; возможность указать точку на графическом экране в
интерактивном режиме с отображением указанных координат <i>X</i>, <i>Y</i> в командной строке и возможности коррекции значений в них; возможность
указания ориентации элементов (без поворота, поворот на 90, поворот на 180, поворот на 270).</P>
</Td><Td>

<P Class=c>Примерный вид изображений:</P>
&nbsp;&nbsp;<Img Src=4_14_z.png></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 15" Style='display: none'></a>
<Table><Tr><Td>

<P>Отрисовка винтов. Программа должна обеспечивать:</P>

<Ul>
 <Li>выбор типа винта (с круглой, плоской, потайной головкой и болта) с помощью кнопок с изображением ImageButton;</Li>
 <Li>возможность задания в EditBox диаметра и длины винта, ширины и высоты головки, длину резьбы;</Li>
 <Li>возможность заполнения полей EditBox параметров винта (диаметра, длины, ширины, высоты головки и длины резьбы) либо по данным из предварительно созданного файла. Размещение и выбор файла с параметрами должно обеспечиваться через стандартное меню AutoCAD;</Li>
 <Li>выбор цвета винта через стандартное меню AutoCAD;</Li>
 <Li>задание точки вставки винта указанием на экране координат с помощью мыши, при котором диалоговое окно временно
  закрывается, давая пользователю возможность указать точку на графическом экране в интерактивном режиме, после чего
  диалоговое окно снова должно появиться на экране с отображением указанных координат <I>X</I>, <I>Y</I> в соответствующих
  полях редактирования EditBox для возможности коррекции значений в них;</Li>
 <Li>задание точки вставки винта указанием координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox в диалоговом окне.</Li>
</Ul>
</Td>
<Td><P Class=c>Примерный вид диалогового окна:</P>&nbsp;&nbsp;<Img Src=../Практика/images/4_15.png></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 16" Style='display: none'></a>

<P>Калькулятор. Программа должна обеспечивать:</P>

<Ul>
 <Li>арифметические операции: сложение, вычитание, умножение, деление, квадратный корень, обратная величина;</Li> 
 <Li>возведение в степень;</Li>
 <Li>перевод величин из метров в дюймы и обратно;</Li>
</Ul>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>



<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 17" Style='display: none'></a>

<P>Калькулятор. Программа должна обеспечивать:</P>

<Ul>
 <Li>арифметические операции: сложение, вычитание, умножение, деление, квадратный корень;</Li>
 <Li>гиперболические синус и косинус;</Li>
 <Li>перевод величин из метров в футы и обратно.</Li>
</Ul>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 18" Style='display: none'></a>
<Table><Tr><Td>

<P>Таймер с обратным отсчётом. Программа должна обеспечить отсчет времени от установленного пользователем до нуля. Минуты и секунды задаются в двух  EditBox’ах. В случае некорректного ввода, выводить в диалоговое окно сообщение об ошибке и устанавливать нулевое значение времени</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_18.png></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 19" Style='display: none'></a>
<Table><Tr><Td>

<P>Сортировка чисел, хранящихся в файле. В файле хранятся положительные, отрицательные, чётные, нечётные, целые и числа с десятичной точкой.
Программа должна обеспечивать чтение чисел из файла, возможность сортировки по возрастанию или убыванию, либо по другим критериям и сохранение
результата в другом файле. Указание местоположения исходного и файла с результатами через стандартное диалоговое окно. Окно программы должно
отображать содержимое исходного файла, и результата.</P>
</Td></Tr>

<Tr><Td><P Class=c>Примерный вид диалоговых окон:</P><Br><Img Src=../Практика/images/4_19_1.png>&nbsp;
<Img Src=../Практика/images/4_19_2.png></P></Td></Tr>

</Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 20" Style='display: none'></a>
<P>Отрисовка 2D и 3D примитивов. Организовать диалог с пользователем через командную строку. Программа должна обеспечивать построение 2D примитивов:
дуги, эллипса, полилинии и пятиугольника; 3D примитивов: тора, призмы, усечённого конуса и шара. 3D примитивы должны представлять собой поверхности.
Пользователь должен иметь возможность задавать точку вставки примитива с помощью ввода координат в командной строке либо с помощью мыши, а также
выбирать цвет примитива с помощью стандартного меню AutoCAD. Размеры примитивов определяются либо из командной строки, либо путём чтения данных из
предварительно созданного файла. Для каждого примитива файл должен иметь соответствующую секцию ([Arc], [Pline], ...) Предустмотреть возможность
построения полилинии, состоящей из линейных и дуговых сегментов. Выбор файла размеров производится через стандартное окно AutoCAD. Для плоских
замкнутых примитивов должна вычисляться и отображаться площадь, а для 3D - объём с выводом данных в виде текста в графическом окне в точке вставки
примитива.</P>

<P Class=c>Вид стандартного диалогового окна выбора файла:<Br>&nbsp;&nbsp;<Img Src=../Практика/images/open_file.png></P>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 21" Style='display: none'></a>

<P>Вращение примитива. Программа должна раз в секунду поворачивать примитив относительно его центра (конца отрезка) с заданным угловым шагом
заданное количество раз. Программа должна обеспечивать диалог с пользователем через командную строку:</P>

<Ul>
 <Li>выбор типа примитива (прямая, квадрат, пятиугольник);</Li>
 <Li>возможность задания параметров вращения (угла на который должен повернуться примитив и углового шага);</Li>
 <Li>выбор цвета винта через стандартное меню AutoCAD;</Li>
 <Li>задание точки вставки примитива указанием на экране координат с помощью мыши с отображением указанных координат <I>X</I>, <I>Y</I> в
 командной строке и возможности коррекции их значений.</Li>
</Ul>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 22" Style='display: none'></a>

<P>Отрисовка круговых массивов примитивов (окружностей, треугольников, квадратов, пятиугольников). Выбор примитивов и задание их параметров - из
командной строки. Пользователь должен иметь возможность задавать точку вставки примитива с помощью мыши, а также выбирать цвет примитива с помощью
стандартного меню AutoCAD.</P>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 23" Style='display: none'></a>
<Table><Tr><Td>

<P>Создание поверхностей вращения (команда AutoCAD revsurf) на основе данных, полученных из файла. В файле содержится информация в произвольном
формате, описывающая полилинию, которая может состоять из отрезков и дуг. Программа должна обеспечивать:</P>

<Ul>
 <Li>выбор цвета поверхности через стандартное меню AutoCAD;</Li>
 <Li>выбор файла с данными об образующей полилинии через стандартное меню AutoCAD;</Li>
 <Li>задание точки вставки центра основания поверхности указанием на экране координат с помощью мыши, при котором диалоговое окно временно
  закрывается, давая пользователю возможность указать точку на графическом экране в интерактивном режиме, после чего диалоговое окно снова должно
  появиться на экране с отображением указанных координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox для возможности коррекции
  значений в них;</Li>
 <Li>задание точки вставки поверхности указанием координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox в диалоговом окне;</Li>
 <Li>возможность задания количества граней поверхности (переменная AutoCAD surftab1) и угол вращения полилинии в полях редактирования EditBox.</Li>
</Ul>

<P>Точка вставки задаёт местоположение поверхности. Ось вращения должна быть параллельна оси <I>OY</I>.</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_01.png></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 24" Style='display: none'></a>
<Table><Tr> <Td>

<P>Создание поверхностей на базе четырёх образующих полилиний (команда AutoCAD edgesurf). В файле содержится информация в произвольном формате,
описывающая четыре полилинии, соединённые друг с другом в началах и концах. Полилинии могут состоять из отрезков и дуг. Программа должна
обеспечивать:</P>

<Ul>
 <Li>выбор цвета поверхности через стандартное меню AutoCAD;</Li>
 <Li>выбор файла с данными об образующей полилинии через стандартное меню AutoCAD;</Li>
 <Li>задание точки вставки поверхности указанием на экране координат с помощью мыши, при котором диалоговое окно временно закрывается, давая
  пользователю возможность указать точку на графическом экране в интерактивном режиме, после чего диалоговое окно снова должно появиться на экране с
  отображением указанных координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox для возможности коррекции значений в них;</Li>
 <Li>задание точки вставки поверхности указанием координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox в диалоговом окне;</Li>
 <Li>возможность задания количества лоскутов разбиения поверхности (переменные AutoCAD surftab1, surftab2) в полях редактирования EditBox.</Li>
</Ul>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_02.png></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 25" Style='display: none'></a>
<Table><Tr><Td>

<P>Построение многоугольников. Диалоговое окно должно обеспечивать выбор многоугольника с количеством углов от пяти до восьми с помощью кнопок с
изображениями ImageButton, а более восьми – с помощью EditBox. Программа должна обеспечивать:</P>

<Ul>
 <Li>при выборе кнопок с изображениями ImageButton в соответствующем окне редактирования EditBox должно отображаться количество углов выбранного
  многоугольника;</Li>
 <Li>выбор цвета многоугольника через стандартное меню AutoCAD;</Li>
 <Li>задание точки вставки центра многоугольника указанием на экране координат с помощью мыши, при котором диалоговое окно временно закрывается,
  давая пользователю возможность указать точку на графическом экране в интерактивном режиме, после чего диалоговое окно снова должно появиться на
  экране с отображением указанных координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox для возможности в коррекции значений в
  них;</Li>
 <Li>задание точки вставки многоугольника указанием координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox в диалоговом
  окне;</Li>
 <Li>возможность задания радиуса описанной окружности в поле редактирования EditBox в формате числа с плавающей точкой;</Li>
 <Li>при выборе количества углов менее трёх и более 255 (ограничения команды AutoCAD polygon) должно выдаваться сообщение об ошибке.</Li>
</Ul>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_03.png></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 26" Style='display: none'></a>
<Table><Tr><Td>

<P>Выравнивание отрезков. При создании чертежа с выключенной опцией "Ortho" возможна ситуация, при которой проектировщик может ошибочно начертить
линии не абсолютно вертикально или горизонтально, а с небольшой погрешностью, т.е. координаты <I>X</I>, <I>Y</I> начала и конца отрезка отличаются в
десятых, или в сотых долях единиц. Диалоговое окно программы должно позволять задать допустимое значение отклонения по каждой оси, менее которого,
отрезок будет считаться не строго горизонтальным, либо вертикальным. Такие отрезки, найденные программой в чертеже должны подвергаться выравниванию.
При этом, координата начальной точки по оси выравнивания записывается в соответствующую координату конечной точки. Отрезками считаются как линии,
так и сегменты полилиний. Программа должна отображать в диалоговом окне сводную информацию об общем количестве найденных отрезков обоих типов, а
также о количестве отрезков обоих типов, которые подвергнутся коррекции. Программа не должна модифицировать полилинии с числом вершин более двух.</P><Br>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_04.png></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 27" Style='display: none'></a>

<P>Отрисовка круговых массивов примитивов (окружностей, треугольников, квадратов и пятиугольников). Размеры и координаты
центра исходного примитива определяются в дополнительном диалоговом окне, вызываемом нажатием кнопки "Размеры примитива".
Оба диалоговых окна должны быть описаны в одном файле. Программа должна обеспечивать:</P>

<Ul>
 <Li>выбор цвета многоугольника через стандартное меню AutoCAD;</Li>
 <Li>задание точки вставки центра массива указанием на экране координат с помощью мыши, при котором диалоговое окно временно закрывается, давая
  пользователю возможность указать точку на графическом экране в интерактивном режиме, после чего диалоговое окно снова должно появиться на экране с
  отображением указанных координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox для возможности в коррекции значений в них;</Li>
 <Li>задание точки вставки центра массива указанием координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox в диалоговом
  окне;</Li>
 <Li>возможность задания радиуса описанной окружности в поле редактирования EditBox в формате числа с плавающей точкой.</Li>
</Ul>

<P Class=c><Img Src=../Практика/images/4_05.png> </P>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 28" Style='display: none'></a>
<P>Отрисовка рамки, штампа и спецификации. Программа должна обеспечивать:</P>

<Ul>
 <Li>выбор элемента для отрисовки, - рамки, штампа или спецификации;</Li>
 <Li>выбор цвета через стандартное меню AutoCAD;</Li>
 <Li>выбор слоя из существующих на текущем чертеже в выпадающем меню;</Li>
 <Li>задание точки вставки левого нижнего угла элементов отрисовки указанием на экране координат с помощью мыши, при котором диалоговое окно временно
  закрывается, давая пользователю возможность указать точку на графическом экране в интерактивном режиме, после чего диалоговое окно снова должно
  появиться на экране;</Li>
 <Li>выбор формата листа (A0, A1, A2, A3). Функция должна быть активизирована только в случае выбора черчения рамки;</Li>
 <Li>заполнение полей штампа как в ручном режиме так и автоматически по данным полученным из предварительно созданного файла произвольного
  формата.</Li>
</Ul>

<Center><Img Src=../Практика/images/4_06_1.png>&nbsp;<Img  Src=../Практика/images/4_06_2.png><Br><Img Src=../Практика/images/open_file.png></Center>
<Br>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 29" Style='display: none'></a>
<Table><Tr><Td>

<P>Извлечение данных о примитивах чертежа. Путём доступа к графической базе данных чертежа получить информацию (имя слоя, номер цвета, тип линии,
координаты вершин и радиус) о примитивах: отрезках, полилиниях, окружностях. Записать полученную информацию в заданный пользователем файл. Он должен
иметь для каждого типа примитва соответствующую секцию ([LINE] [POLYLINE] [CIRCLE]). Если примитив имеет цвет "ПоСлою" (ByLayer) или слой по
умолчанию, то эта информация также должна быть отражена в выходном файле.</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:<Br>&nbsp;&nbsp;<Img Src=../Практика/images/4_07.png></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 30" Style='display: none'></a>
<Table><Tr><Td>

<P>Создание октантного дерева. Диалоговое окно должно обеспечивать ввод уровня разбиения и возможность выбора многоугольника, для которого будет
строиться октантное дерево. Октантное дерево – это структура данных, которая представляет собой плоское тело в виде рекурсивного подразделения
двухмерного пространства на прямоугольные блоки (в нашей задаче квадраты).</P>

<P>Процедура построения октантного дерева. Сначала создаётся квадрат, в который многоугольник помещается целиком. Для этого находится максимальные и
минимальные координаты по Х и по Y. Далее находится сторона квадрата и его центр. Этот квадрат называется корневым октантом. Затем корневой октант
делится на 4 октанта, после чего анализируется их положение по отношению к многоугольнику. Если октант находится полностью внутри многоугольника, он
считается «чёрным»; если снаружи – «белым». Если же октант частично лежит внутри многоугольника, а частично – снаружи, то он считается «серым» и
делится на четыре октанта меньшего размера. Чёрные и белые октанты дальше не делятся. Процедура продолжается до тех пор, пока не будет достигнут
заданный уровень разбиения. «Цвет» определяется следующим образом: проверяется, пересекаются ли стороны октанта со сторонами многоугольника (с
помощью функции AutoLisp inters). Если стороны октанта пересекаются со сторонами многоугольника, то октант считается «серым». Иначе октант лежит
внутри либо снаружи многоугольника. Чтобы определить его «цвет» подсчитывается количество пересечений отрезка лежащего между центром октанта и одной
из вершин корневого октанта со сторонами многоугольника. Если количество пересечений чётное или ноль, то квадрат лежит снаружи многоугольника и
считается «белым». Иначе если количество пересечений нечётное, то он лежит внутри многоугольника и считается «чёрным». На чертеже рисуются только
октанты внутри треугольника</P>
</Ul>
</Td>
<Td><P Class=c>Примерный вид диалогового окна:<Br>
&nbsp;&nbsp;<Img Src=../Практика/images/4_08.png><Br><Br>Процесс создания октодерева:<Br> <Img Src=../Практика/images/4_08.gif></P></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Hr Width="90%" Color="#7685C6" Align="Right">
<Br>
<p class="h6">582472</p>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 1" Style='display: none'></a>
<Table><Tr><Td>

<P>Отрисовка полилиний по данным, полученным из предварительно созданного файла в произвольном формате.
Предусмотреть функцию сглаживания полилинии и возможность её замкнуть (элемент Toggle). Программа должна обеспечивать:</P>

<Ul>
 <Li>выбор цвета полилинии через стандартное меню AutoCAD с отображением его в диалоговом окне;</Li>
 <Li>задание точки вставки начала полилинии указанием на экране координат с помощью мыши, при котором диалоговое окно временно закрывается, давая
  пользователю возможность указать точку на графическом экране в интерактивном режиме, после чего диалоговое окно снова должно появиться на экране с
  отображением указанных координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox для возможности в коррекции значений в них;</Li>
 <Li>задание точки вставки полилинии указанием координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox в диалоговом окне;</Li>
 <Li>возможность выбора файла с помощью стандартного диалогового окна.</Li>
</Ul>
</Td>
<Td><P Class=c>Примерный вид диалогового окна:<Br>&nbsp;&nbsp;<Img Src=../Практика/images/4_09.png></P></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>
<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 2" Style='display: none'></a>
<Table><Tr><Td>

<P>Построение зубчатого колеса. Программа должна обеспечивать:</P>

<Ul>
 <Li>выбор вида зубцов (треугольные либо прямоугольные) с помощью ImageButton;</Li>
 <Li>задание внутреннего и внешнего радиуса колеса, длины стороны зубца в полях редактирования EditBox;</Li>
 <Li>число зубцов вычисляется на основании внешнего радиуса колеса и длины стороны зубца;</Li>
 <Li>выбор цвета полилинии через стандартное меню AutoCAD с отображением его в диалоговом окне;</Li>
 <Li>задание точки вставки центра зубчатого колеса указанием на экране координат с помощью мыши, при котором диалоговое окно временно закрывается,
  давая пользователю возможность указать точку на графическом экране в интерактивном режиме, после чего диалоговое окно снова должно появиться на
  экране с отображением указанных координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox для возможности в коррекции значений в
  них;</Li>
 <Li>задание точки вставки центра зубчатого колеса указанием координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox в
  диалоговом окне.</Li>
</Ul>
</Td>
<Td><P Class=c>Примерный вид диалогового окна:<Br>&nbsp;&nbsp;<Img Src=../Практика/images/4_10.png></P></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 3" Style='display: none'></a>
<P>Отрисовка 2D и 3D примитивов. Организовать диалог с пользователем через командную строку. Программа должна обеспечивать построение 2D примитивов:
дуги, эллипса, полилинии и пятиугольника; 3D примитивов: тора, призмы, усечённого конуса и шара. 3D примитивы должны представлять собой поверхности.
Пользователь должен иметь возможность задавать точку вставки примитива с помощью ввода координат в командной строке либо с помощью мыши, а также
выбирать цвет примитива с помощью стандартного меню AutoCAD. Размеры примитивов определяются либо из командной строки, либо путём чтения данных из
предварительно созданного файла. Предустмотреть возможность построения полилинии, состоящей из линейных и дуговых сегментов. Выбор файла размеров
производится через стандартное окно AutoCAD. Для плоских замкнутых примитивов должна вычисляться и отображаться площадь, а для 3D - объём с выводом
данных в виде текста в графическом окне в точке вставки примитива.</P>

<P Class=c>Вид стандартного диалогового окна выбора файла:<Br>&nbsp;&nbsp;<Img Src=../Практика/images/open_file.png></P>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 4" Style='display: none'></a>
<Table><Tr><Td>

<P>Извлечение данных о примитивах чертежа. Путём доступа к графической базе данных чертежа получить информацию (имя слоя, номер цвета, тип линии,
координаты вершин и радиус) о примитивах: точках, полилиниях, сплайнах. Записать полученную информацию в заданный пользователем файл.</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>&nbsp;&nbsp;<Img Src=../Практика/images/4_12.png></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 5" Style='display: none'></a>
<Table><Tr><Td>

<P>Отрисовка винтов. Программа должна обеспечивать:</P>

<Ul>
 <Li>выбор типа винта (с круглой, плоской, потайной головкой и болта) с помощью выпадающего меню;</Li>
 <Li>возможность задания в EditBox диаметра и длины винта, ширины и высоты головки, длину резьбы;</Li>
 <Li>возможность заполнения полей EditBox параметров винта (диаметра, длины, ширины, высоты головки и длины резьбы) либо по данным из предварительно созданного файла. Размещение и выбор файла с параметрами должно обеспечиваться через стандартное меню AutoCAD;</Li>
 <Li>выбор цвета винта через стандартное меню AutoCAD;</Li>
 <Li>задание точки вставки винта указанием на экране координат с помощью мыши, при котором диалоговое окно временно
  закрывается, давая пользователю возможность указать точку на графическом экране в интерактивном режиме, после чего
  диалоговое окно снова должно появиться на экране с отображением указанных координат <I>X</I>, <I>Y</I> в соответствующих
  полях редактирования EditBox для возможности коррекции значений в них;</Li>
 <Li>задание точки вставки винта указанием координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox в диалоговом окне.</Li>
</Ul>
</Td>
<Td><P Class=c>Примерный вид диалогового окна:</P>&nbsp;&nbsp;<Img Src=../Практика/images/4_13.png></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 6" Style='display: none'></a>
<Table><Tr><Td>

<P>Выравнивание отрезков. При создании чертежа с выключенной опцией "Ortho" возможна ситуация, при которой проектировщик может ошибочно начертить
линии не абсолютно вертикально или горизонтально, а с небольшой погрешностью, т.е. координаты <I>X</I>, <I>Y</I> начала и конца отрезка отличаются в
десятых, или в сотых долях единиц. Диалоговое окно программы должно позволять задать допустимое значение отклонения по каждой оси, менее которого,
отрезок будет считаться не строго горизонтальным, либо вертикальным. Такие отрезки, найденные программой в чертеже должны подвергаться выравниванию.
При этом производится коррекция как начальных, так и конечных координат отрезка относительно его середины. Отрезками считаются как линии, так и
сегменты полилиний. Программа должна отображать в диалоговом окне сводную информацию об общем количестве найденных отрезков обоих типов, а также о
количестве отрезков обоих типов, которые подвергнутся коррекции.</P>
</Td>
<Td><P Class=c>Примерный вид диалогового окна:</P>&nbsp;&nbsp;<Img Src=../Практика/images/4_14.png></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 7" Style='display: none'></a>
<Table><Tr><Td>

<P>Отрисовка винтов. Программа должна обеспечивать:</P>

<Ul>
 <Li>выбор типа винта (с круглой, плоской, потайной головкой и болта) с помощью кнопок с изображением ImageButton;</Li>
 <Li>возможность задания в EditBox диаметра и длины винта, ширины и высоты головки, длину резьбы;</Li>
 <Li>возможность заполнения полей EditBox параметров винта (диаметра, длины, ширины, высоты головки и длины резьбы) либо по данным из предварительно созданного файла. Размещение и выбор файла с параметрами должно обеспечиваться через стандартное меню AutoCAD;</Li>
 <Li>выбор цвета винта через стандартное меню AutoCAD;</Li>
 <Li>задание точки вставки винта указанием на экране координат с помощью мыши, при котором диалоговое окно временно
  закрывается, давая пользователю возможность указать точку на графическом экране в интерактивном режиме, после чего
  диалоговое окно снова должно появиться на экране с отображением указанных координат <I>X</I>, <I>Y</I> в соответствующих
  полях редактирования EditBox для возможности коррекции значений в них;</Li>
 <Li>задание точки вставки винта указанием координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования EditBox в диалоговом окне.</Li>
</Ul>
</Td>
<Td><P Class=c>Примерный вид диалогового окна:</P>&nbsp;&nbsp;<Img Src=../Практика/images/4_15.png></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 8" Style='display: none'></a>
<Table><Tr><Td>

<P>Калькулятор. Программа должна обеспечивать:</P>

<Ul>
 <Li>арифметические операции: сложение, вычитание, умножение, деление, квадратный корень, обратная величина, вычисление процентов;</Li> 
 <Li>операции с положительными/отрицательными числами;</Li>
 <Li>операции с памятью;</Li>
 <Li>возведение в степень;</Li>
 <Li>вычисление натурального логарифма;</Li>
 <Li>перевод величин из метров в дюймы и обратно;</Li>
 <Li>возможность коррекции исходных данных;</Li>
 <Li>вывод информации об ошибках при делении на нуль, при вычислении корня и логарифма отрицательного числа, возведении нуля в отрицательную степень.</Li>
</Ul>
</Td>
<Td><P Class=c>Примерный вид диалогового окна:</P>&nbsp;&nbsp;<Img Src=../Практика/images/4_16.png></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>



<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 9" Style='display: none'></a>
<Table><Tr><Td>

<P>Калькулятор. Программа должна обеспечивать:</P>

<Ul>
 <Li>арифметические операции: сложение, вычитание, умножение, деление, квадратный корень;</Li>
 <Li>операции с положительными/отрицательными числами;</Li>
 <Li>операции со скобками произвольной вложенности;</Li>
 <Li>гиперболические синус и косинус;</Li>
 <Li>перевод величин из метров в футы и обратно;</Li>
 <Li>возможность коррекции исходных данных;</Li>
 <Li>вывод информации об ошибках при делении на нуль, при вычислении корня.</Li>
</Ul>
</Td>
<Td><P Class=c>Примерный вид диалогового окна:</P>&nbsp;&nbsp;<Img Src=../Практика/images/4_17.png></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 10" Style='display: none'></a>
<Table><Tr><Td>

<P>Таймер с обратным отсчётом. Программа должна обеспечить отсчет времени от установленного пользователем до нуля. Минуты и секунды задаются в двух  EditBox’ах. В случае некорректного ввода, выводить в диалоговое окно сообщение об ошибке и устанавливать нулевое значение времени</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_18.png></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 11" Style='display: none'></a>
<Table><Tr><Td>

<P>Сортировка чисел, хранящихся в файле. В файле хранятся положительные, отрицательные, чётные, нечётные, целые и числа с десятичной точкой. Программа должна обеспечивать чтение чисел из файла, возможность сортировки по возрастанию или убыванию, либо по другим критериям и сохранение результата в другом файле. Указание местоположения исходного и файла с результатами через стандартное диалоговое окно. Окно программы должно отображать содержимое исходного файла, и результата.</P>
</Td></Tr>

<Tr><Td><P Class=c>Примерный вид диалоговых окон:</P><Br><Img Src=../Практика/images/4_19_1.png>&nbsp;<Img Src=../Практика/images/4_19_2.png></P></Td></Tr>

</Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 12" Style='display: none'></a>
<Table><Tr><Td>

<P>Вращение примитива. Программа должна раз в секунду поворачивать примитив относительно его центра (конца отрезка) с заданным угловым шагом
заданное количество раз. Программа должна обеспечивать:</P>

<Ul>
 <Li>выбор типа примитива (прямая, прямоугольник, пятиугольник) с помощью кнопок выбора radio_button;</Li>
 <Li>возможность задания параметров вращения с помощью слайдеров (угла на который должен повернуться примитив и углового шага);</Li>
 <Li>выбор цвета винта через стандартное меню AutoCAD;</Li>
 <Li>задание точки вставки примитива указанием на экране координат с помощью мыши, при котором диалоговое окно временно
  закрывается, давая пользователю возможность указать точку на графическом экране в интерактивном режиме, после чего
  диалоговое окно снова должно появиться на экране с отображением указанных координат <I>X</I>, <I>Y</I> в соответствующих
  полях редактирования edit_box для возможности коррекции значений в них;</Li>
 <Li>задание точки вставки примитива указанием координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования edit_box в диалоговом окне.</Li>
</Ul>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_20.png></Td>
</Tr></Table>

<P></P>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 13" Style='display: none'></a>
<Table><Tr><Td>

<P>Извлечение данных о примитивах чертежа. Путём доступа к графической базе данных чертежа получить информацию (имя слоя, номер цвета, тип линии,
координаты вершин и радиус) о примитивах: окружностях, полилиниях, сплайнах. Записать полученную информацию в заданный пользователем файл.
Диалоговое окно должно иметь возможность выбора типов примитивов, и отображать их количество в соответствии с видом диалогового окна на рисунке.</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_21.png></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 14" Style='display: none'></a>
<Table><Tr><Td>

<P>Извлечение данных о примитивах чертежа. Путём доступа к графической базе данных чертежа получить информацию (имя слоя, номер цвета, тип линии, координаты вершин, начальной и конечной точки) о примитивах: линиях, полилиниях, сплайнах. Записать полученную информацию в заданный пользователем файл. Диалоговое окно должно иметь возможность выбора типов примитивов, и отображать их количество в соответствии с видом диалогового окна на рисунке.</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_22.png></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 15" Style='display: none'></a>
<Table><Tr><Td>

<P>Отрисовка массивов примитивов. Пользователь должен иметь возможность задавать точку вставки примитива с помощью ввода координат в диалоговом окне
или с помощью мыши, а также выбирать цвет примитива с помощью стандартного меню AutoCAD. Размеры примитивов определяются в дополнительном диалоговом
окне.</P>
</Td>

<Tr><Td ColSpan=2><Center><Img Src=../Практика/images/4_23_1.png>&nbsp;<Img Src=../Практика/images/4_23_2.png></Center></Td></Tr>
</Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 16" Style='display: none'></a>
<Table><Tr><Td>

<P>Определение пересечения объектов. Организовать диалоговое окно с кнопкой выбора примитива. По нажатию на кнопку окно закрывается, давая
пользователю возможность мышью выбрать первый примитив. Пользователь выбирает (ENTSEL) отрезок, окружность или прямоугольник (PLINE), после чего
окно восстанавливается с отображением в нём имени выбранного примитива. Процедура повторяется для выбора второго примитива. По нажатию на кнопку
"OK" выводится сообщение о пересечении или не пересечении выбранных объектов.</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_24.png></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 17" Style='display: none'></a>
<Table><Tr><Td>

<P>Объединение сегментов линий в одну полилинию. Диалоговое окно имеет поля редактирования (dX,dY) для максимальных значений различия координат
конечных точек соседних сегментов будующей полилинии. Кнопкой "Select" выбираются сегменты предполагаемой полилинии, информация о которых
отображается в ListBox (номер сегмента, X, Y - координаты начальных и конечных точек сегментов). По нажатию на "OK" сегменты, значения координат
которых соответствуеют условию (менее заданных dX, dY), объединяются в единую полилинию.</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_25.png></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 18" Style='display: none'></a>
<Table><Tr><Td>

<P>Извлечение данных о примитивах чертежа. Путём доступа к графической базе данных чертежа получить информацию (номер цвета, тип линии, координаты
вершин и радиус) о примитивах: линиях, окружностях и полилиниях. Вывести полученную информацию в соответствующее выбранному типу примитивов
диалоговое окно. Предусмотреть возможность пролистывания примитивов с отображением информации о них в EditBox'ах.</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_26_1.png></Td></Tr>
<Tr><Td ColSpan=2><Center><Img Src=../Практика/images/4_26_2.png> <Img Src=../Практика/images/4_26_3.png> <Img Src=../Практика/images/4_26_4.png></Center></Td></Tr>
</Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 19" Style='display: none'></a>
<P>Отрисовка 2D и 3D примитивов. Организовать диалог с пользователем через командную строку. Программа должна обеспечивать построение 2D примитивов:
эллипсов, дуг, полилиний и пятиугольников; 3D примитивов: тора, призмы, усеченного конуса и шара. Пользователь должен иметь возможность задавать
точку вставки примитива с помощью ввода координат в командной строке либо с помощью мыши, а также выбирать цвет примитива с помощью стандартного
меню AutoCAD. Размеры примитивов определяются путём чтения данных из предварительно созданного файла. Выбор файла размеров производится через
стандартное окно AutoCAD.</P>
<Br>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 20" Style='display: none'></a>
<Table><Tr><Td>

<P>Отрисовка 2D и 3D примитивов. Диалоговое окно должно обеспечивать выбор типа 2D примитивов: эллипсов, дуг, полилиний и пятиугольников; 3D
примитивов: тора, призмы, усеченного конуса и шара. Пользователь должен иметь возможность задавать точку вставки примитива с помощью ввода
координат в командной строке либо с помощью мыши, а также выбирать цвет примитива с помощью стандартного меню AutoCAD. Размеры примитивов
определяются путём чтения данных из предварительно созданного файла. Выбор файла размеров производится через стандартное окно AutoCAD.</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
<Tr><Td ColSpan=2><Center><Img Src=../Практика/images/4_28.png> <Img Src=../Практика/images/4_28_2.png></Center></Td></Tr>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 21" Style='display: none'></a>
<Table><Tr><Td>

<P>Нахождение кластеров отрезков и объединение их в единые полилинии. Диалоговое окно имеет кнопку "Поиск" по которой программа просматривает весь чертёж в поисках нескольких линий, следующих друг за другом, которые могут быть склеены в единую полилинию. Информация о таких "образованиях" выводится в ListBox (номер кластера, количество линий в кластере). По кнопке "OK" линии и дуги кластеров объединяются в единые полилинии и перекрашиваются в красный цвет.</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_25.png></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 22" Style='display: none'></a>
<Table><Tr><Td>

<P>Проектирование фасадов кухонной мебели. Диалоговое окно должно обеспечивать выбор вида фасада с отображением соответствующей картинки (дверца глухая, двойная, дверца со стеклом, ящик, ...), выбор положения ручки (слева, справа, по центру). Пользователь должен иметь возможность задавать точку вставки с помощью ввода координат в командной строке либо с помощью мыши. Размеры фасадов задаются из нескольких возможных путём применения масштабного коэффициента (1, 1.5, 2).</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_30.gif></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>



<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 23" Style='display: none'></a>
<Table><Tr><Td>

<P>Каталог радиоэлементов. Диалоговое окно должно обеспечивать:</P>

<Ul>
 <Li>выбор радиоэлемента с отображением соответствующей картинки (резистр, транзистор, диод, конденсатор, источник);</Li>
 <Li>выбор цвета радиоэлемента через стандартное меню AutoCAD;</Li>
 <Li>возможность указать точку на графическом экране в интерактивном режиме, после чего диалоговое окно снова должно появиться на экране с
  отображением указанных координат <i>X</i>, <i>Y</i> в соответствующих полях редактирования EditBox для возможности коррекции значений в них;</Li>
 <Li>возможность масштабирования элементов путём применения коэффициента (1, 1.5, 2).</Li>
</Ul>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_31.gif></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 24" Style='display: none'></a>
<Table><Tr><Td>

<P>Вращение примитива. Программа должна раз в секунду поворачивать примитив относительно его центра (конца отрезка) с заданным угловым шагом
заданное количество раз. Программа должна обеспечивать:</P>

<Ul>
 <Li>выбор типа примитива (прямая, прямоугольник, пятиугольник) с помощью кнопок выбора radio_button;</Li>
 <Li>возможность задания параметров вращения с помощью слайдеров (угла на который должен повернуться примитив и углового шага);</Li>
 <Li>выбор цвета винта через стандартное меню AutoCAD;</Li>
 <Li>задание точки вставки примитива указанием на экране координат с помощью мыши, при котором диалоговое окно временно
  закрывается, давая пользователю возможность указать точку на графическом экране в интерактивном режиме, после чего
  диалоговое окно снова должно появиться на экране с отображением указанных координат <I>X</I>, <I>Y</I> в соответствующих
  полях редактирования edit_box для возможности коррекции значений в них;</Li>
 <Li>задание точки вставки примитива указанием координат <I>X</I>, <I>Y</I> в соответствующих полях редактирования edit_box в диалоговом окне.</Li>
</Ul>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_20.png></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 25" Style='display: none'></a>
<Table><Tr><Td>

<P>Извлечение данных о примитивах чертежа. Путём доступа к графической базе данных чертежа получить информацию (имя слоя, номер цвета, тип линии, координаты вершин и радиус) о примитивах: окружностях, полилиниях, сплайнах. Записать полученную информацию в заданный пользователем файл.</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_21.png></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 26" Style='display: none'></a>
<Table><Tr><Td>

<P>Извлечение данных о примитивах чертежа. Путём доступа к графической базе данных чертежа получить информацию (имя слоя, номер цвета, тип линии, координаты вершин, начальной и конечной точки) о примитивах: линиях, полилиниях, сплайнах. Записать полученную информацию в заданный пользователем файл. Диалоговое окно должно иметь возможность выбора типов примитивов, и отображать их количество в соответствии с видом диалогового окна на рисунке.</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_22.png></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 27" Style='display: none'></a>
<Table><Tr><Td>

<P>Отрисовка круговых массивов окружностей, треугольников, квадратов. Пользователь должен иметь возможность задавать точку вставки примитива с
помощью ввода координат в диалоговом окне или с помощью мыши, а также выбирать цвет примитива с помощью стандартного меню AutoCAD. Размеры
примитивов определяются в том же диалоговом окне. При ошибках задания параметров программа должна выдать соответствующее сообщение.</P>
</Td>

<Tr><Td ColSpan=2><Center><Img Src=../Практика/images/4_23_1.png>&nbsp;<Img Src=../Практика/images/4_23_2.png></Center></Td></Tr>
</Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 28" Style='display: none'></a>
<Table><Tr><Td>

<P>Определение пересечения линий, прямоугольников, окружностей. Организовать диалоговое окно с кнопкой выбора примитива. По нажатию на кнопку окно должноз
акрывается, давая пользователю возможность мышью выбрать первый примитив. Пользователь выбирает (ENTSEL) линию, окружность или прямоугольник
(PLINE), после чего окно восстанавливается с отображением в нём имени выбранного примитива. Процедура повторяется для выбора второго примитива. По
нажатию на кнопку "OK" выводится сообщение о пересечении или не пересечении выбранных объектов.</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_24.png></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 29" Style='display: none'></a>
<Table><Tr><Td>

<P>Отрисовка схемных изображений транзисторов. Программа в командной строке должна запрашивать выбор типа транзистора (P-N-P, N-P-N, N-канальный полевой, P-канальный полевой); выбор цвета радиоэлемента через стандартное меню AutoCAD; возможность указать точку на графическом экране в интерактивном режиме с отображением указанных координат X, Y в командной строке и возможности коррекции значений в них; возможность указания ориентации элементов (без поворота, поворот на 90, поворот на 180, поворот на 270).
</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_25.png></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 30" Style='display: none'></a>
<Table><Tr><Td>

<P>Извлечение данных о примитивах чертежа. Путём доступа к графической базе данных чертежа получить информацию (номер цвета, тип линии, координаты
вершин и радиус) о примитивах: линиях, окружностях и полилиниях. Вывести полученную информацию в соответствующее выбранному типу примитивов
диалоговое окно. Предусмотреть возможность пролистывания примитивов с отображением информации о них в EditBox'ах.</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_26_1.png></Td></Tr>
<Tr><Td ColSpan=2><Center><Img Src=../Практика/images/4_26_2.png> <Img Src=../Практика/images/4_26_3.png> <Img Src=../Практика/images/4_26_4.png></Center></Td></Tr>
</Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>


<!--

<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 8" Style='display: none'></a>

<P>Отрисовка 2D и 3D примитивов. Организовать диалог с пользователем через командную строку. Программа должна обеспечивать построение 2D примитивов:
дуги, эллипса, полилинии и семиугольника; 3D примитивов: тора, призмы, конуса и шара. 3D примитивы должны представлять собой поверхности.
Пользователь должен иметь возможность задавать точку вставки примитива с помощью ввода координат в командной строке либо с помощью мыши, а также
выбирать цвет примитива с помощью стандартного меню AutoCAD; для 3D примитивов задавать количество граней поверхности (системная переменная AutoCAD
surftab1). Размеры примитивов определяются либо из командной строки, либо путём чтения данных из предварительно созданного файла. Для каждого
примитива файл должен иметь соответствующую секцию ([Arc], [Pline], [Torus]...). Предустмотреть возможность построения полилинии, состоящей из линейных и
дуговых сегментов. Выбор файла размеров производится через стандартное окно AutoCAD. Для плоских замкнутых примитивов должна вычисляться и
отображаться площадь, а для 3D - объём с выводом данных в виде текста в графическом окне в точке вставки примитива.</P>
<Br>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 9" Style='display: none'></a>
<Table><Tr><Td>

<P>Отрисовка 2D и 3D примитивов. Диалоговое окно должно обеспечивать выбор типа 2D примитивов: эллипсов, дуг, полилиний и пятиугольников; 3D
примитивов: тора, призмы, усеченного конуса и шара. Пользователь должен иметь возможность задавать точку вставки примитива с помощью ввода
координат в командной строке либо с помощью мыши, а также выбирать цвет примитива с помощью стандартного меню AutoCAD. Размеры примитивов
определяются путём чтения данных из предварительно созданного файла. Выбор файла размеров производится через стандартное окно AutoCAD по кнопке
"Размер". Для каждого примитива файл должен иметь соответствующую секцию ([Arc], [Pline], [Torus]...)</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
<Tr><Td ColSpan=2><Center><Img Src=../Практика/images/4_28.png> <Img Src=../Практика/images/4_28_2.png></Center></Td></Tr>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 10" Style='display: none'></a>
<Table><Tr><Td>

<P>Каталог схемных изображений транзисторов. Диалоговое окно должно обеспечивать:</P>

<Ul>
 <Li>выбор транзистора с отображением соответствующей картинки (P-N-P, N-P-N, N-канальный полевой, P-канальный полевой);</Li>
 <Li>выбор транзистора радиоэлемента через стандартное меню AutoCAD;</Li>
 <Li>возможность указать точку на графическом экране в интерактивном режиме, после чего диалоговое окно снова должно появиться на экране с
  отображением указанных координат <i>X</i>, <i>Y</i> в соответствующих полях редактирования EditBox для возможности коррекции значений в них;</Li>
 <Li>Вместо "возможность масштабирования элементов путём применения коэффициента (1, 1.5, 2)" должна быть возможность поворота элемента на 90, 180, 270 градусов.</Li>
</Ul>

</Td><Td>

<P Class=c>Примерный вид изображений:</P>
<Img Src=4_03_z.png>&nbsp;<Img Src=../Практика/images/4_31.gif></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 11" Style='display: none'></a>
<Table><Tr><Td>

<P>Проектирование фасадов кухонной мебели. Диалоговое окно должно обеспечивать выбор вида фасада с отображением соответствующей картинки (дверца глухая, двойная, дверца со стеклом, ящик, ...), выбор положения ручки (слева, справа, по центру). Пользователь должен иметь возможность задавать точку вставки с помощью ввода координат в командной строке либо с помощью мыши. Размеры фасадов задаются из нескольких возможных путём применения масштабного коэффициента (1, 1.5, 2).</P>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_30.gif></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>



<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 12" Style='display: none'></a>
<Table><Tr><Td>

<P>Каталог радиоэлементов. Диалоговое окно должно обеспечивать:</P>

<Ul>
 <Li>выбор радиоэлемента с отображением соответствующей картинки (резистр, транзистор, диод, конденсатор, источник);</Li>
 <Li>выбор цвета радиоэлемента через стандартное меню AutoCAD;</Li>
 <Li>возможность указать точку на графическом экране в интерактивном режиме, после чего диалоговое окно снова должно появиться на экране с
  отображением указанных координат <i>X</i>, <i>Y</i> в соответствующих полях редактирования EditBox для возможности коррекции значений в них;</Li>
 <Li>Вместо "возможность масштабирования элементов путём применения коэффициента (1, 1.5, 2)" должна быть возможность поворота элемента на 90, 180, 270 градусов.</Li>
</Ul>
</Td><Td>

<P Class=c>Примерный вид диалогового окна:</P>
&nbsp;&nbsp;<Img Src=../Практика/images/4_31.gif></Td>
</Tr></Table>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<!--



<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 21" Style='display: none'></a>

<P>Извлечение данных о примитивах чертежа. Путём доступа к графической базе данных чертежа получить информацию (имя слоя, номер цвета, тип линии,
координаты вершин и радиус) о примитивах: окружностях, полилиниях, сплайнах. Записать полученную информацию в заданный пользователем файл.
Диалог с пользователем - из командной строки с возможностью указания типов примитивов и имени сохраняемого файла.</P>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 22" Style='display: none'></a>

<P>Извлечение данных о примитивах чертежа. Путём доступа к графической базе данных чертежа получить информацию (имя слоя, номер цвета, тип линии,
координаты вершин, начальной и конечной точки) о примитивах: линиях, полилиниях, сплайнах. Записать полученную информацию в заданный пользователем
файл. Диалог с пользователем - из командной строки с возможностью указания типов примитивов и имени сохраняемого файла.</P>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>









<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 24" Style='display: none'></a>

<P>Определение пересечения объектов. Организовать диалог с пользователем через командную строку. Примитивы должны выбираться мышью.
Пользователь выбирает (ENTSEL) пару из любых двух примитивов: отрезок, окружность или прямоугольник (PLINE). После чего выводится сообщение о
пересечении или не пересечении выбранных объектов.</P>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 25" Style='display: none'></a>

<P>Объединение сегментов линий в одну полилинию. В командной строке программа должна запрашивать максимальные значения различия координат
конечных точек соседних сегментов будущей полилинии (dX,dY), затем предлагать выбор сегментов предполагаемой полилинии. После чего, сегменты со
значениями координат, которые соответствуют условию (менее заданных dX, dY), объединяются в единую полилинию.</P>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 26" Style='display: none'></a>

<P>Извлечение данных о примитивах чертежа. Путём доступа к графической базе данных чертежа получить информацию (номер цвета, тип линии, координаты
вершин и радиус) о примитивах: линиях, окружностях и полилиниях. В командной строке программа должна запросить тип примитива, имя файла для
сохранения, и записать туда извлечённую информацию.</P>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 27" Style='display: none'></a>
<P>Отрисовка 2D и 3D примитивов. Организовать диалог с пользователем через командную строку. Программа должна обеспечивать построение 2D примитивов:
эллипсов, дуг, полилиний и пятиугольников; 3D примитивов: тора, призмы, усеченного конуса и шара. Пользователь должен иметь возможность задавать
точку вставки примитива с помощью ввода координат в командной строке либо с помощью мыши, а также выбирать цвет примитива с помощью стандартного
меню AutoCAD. Размеры примитивов определяются путём чтения данных из предварительно созданного файла. Выбор файла размеров производится через
стандартное окно AutoCAD. 3D примитивы создаются либо с помощью поверхностей (revsurf - усечённый конус, шар), либо твердотельные.</P>
<Br>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 28" Style='display: none'></a>

<P>Отрисовка 2D и 3D примитивов. Диалог с пользователем - через командную строку. Программа должна обеспечивать выбор типа 2D примитивов:
эллипсов, окружностей, полилиний и шестиугольников; 3D примитивов: пирамиды, призмы, усеченного конуса и куба.
Пользователь должен иметь возможность задавать точку вставки примитива с помощью ввода
координат в командной строке либо с помощью мыши, а также выбирать цвет примитива с помощью стандартного меню AutoCAD. Размеры примитивов
определяются путём чтения данных из предварительно созданного файла. Выбор файла размеров производится через стандартное окно AutoCAD (getfiled).
3D примитивы создаются либо с помощью поверхностей (revsurf - усечённый конус, шар), либо твердотельные.</P>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 29" Style='display: none'></a>

<P>Нахождение кластеров отрезков и объединение их в единые полилинии. В командной строке программа должна запрашивать максимальные значения различия
координат конечных точек соседних сегментов будущей полилинии (dX,dY), программа просматривает весь чертёж в поисках нескольких линий, следующих
друг за другом, которые могут быть склеены в единую полилинию. После чего, сегменты со значениями координат, которые соответствуют условию (менее
заданных dX, dY), объединяются в единую полилинию.</P>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 30" Style='display: none'></a>

<P>Проектирование фасадов кухонной мебели. Программа в командной строке должна запрашивать выбор вида фасада (дверца глухая, двойная, дверца со
стеклом, ящик, ...), выбор положения ручки (слева, справа, по центру). Пользователь должен иметь возможность задавать точку вставки с помощью ввода
координат в командной строке либо с помощью мыши. Размеры фасадов задаются из нескольких возможных путём применения масштабного коэффициента (1, 1.5,
2).</P>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>



<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 31" Style='display: none'></a>

<P>Каталог радиоэлементов. Программа в командной строке должна запрашивать выбор выбор радиоэлемента (резистр, транзистор, диод, конденсатор,
источник); выбор цвета радиоэлемента через стандартное меню AutoCAD; возможность указать точку на графическом экране в интерактивном режиме
с отображением указанных координат <i>X</i>, <i>Y</i> в командной строке и возможности коррекции значений в них; возможность масштабирования
элементов путём применения коэффициента (1, 1.5, 2).</P>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>




<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 32" Style='display: none'></a>

<P>Выравнивание отрезков. При создании чертежа с выключенной опцией "Ortho" возможна ситуация, при которой проектировщик может ошибочно начертить
линии не абсолютно вертикально или горизонтально, а с небольшой погрешностью, т.е. координаты <I>X</I>, <I>Y</I> начала и конца отрезка отличаются в
десятых, или в сотых долях единиц. Программа в командной строке должна запросить выбор линии, и дать возможность её выбрать на экране с помощью мыши
(entsel), а также задать допустимое значение отклонения по каждой оси, менее которого, отрезок будет считаться не строго горизонтальным, либо
вертикальным. Такие отрезки, выбранные пользователем в чертеже должны подвергаться выравниванию.
При этом, координата начальной точки по оси выравнивания записывается в соответствующую координату конечной точки. Отрезками считаются как линии,
так и сегменты полилиний. Программа не должна модифицировать полилинии с числом вершин более двух.</P><Br>

<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>













<Div Class="post_body">
<A Href='javascript:;'><Div Class="sp-body" Title="Вариант 34" Style='display: none'></a>
<Table><Tr><Td>

<P>Выравнивание отрезков. При создании чертежа с выключенной опцией "Ortho" возможна ситуация, при которой проектировщик может ошибочно начертить
линии не абсолютно вертикально или горизонтально, а с небольшой погрешностью, т.е. координаты <I>X</I>, <I>Y</I> начала и конца отрезка отличаются в
десятых, или в сотых долях единиц. Диалоговое окно программы должно позволять задать допустимое значение отклонения по каждой оси, менее которого,
отрезок будет считаться не строго горизонтальным, либо вертикальным. Такие отрезки, найденные программой в чертеже должны подвергаться выравниванию.
При этом производится коррекция как начальных, так и конечных координат отрезка относительно его середины. Отрезками считаются как линии, так и
сегменты полилиний. Программа должна отображать в диалоговом окне сводную информацию об общем количестве найденных отрезков обоих типов, а также о
количестве отрезков обоих типов, которые подвергнутся коррекции.</P>
</Td>
<Td><P Class=c>Примерный вид диалогового окна:</P>&nbsp;&nbsp;<Img Src=../Практика/images/4_14.png></Td>
</Tr></Table>
<Hr Width="90%" Color="#7685C6" Align="Right"><Br><Br>
</Div>-->




 </Td>
</Tr>
<Tr>
  <Td>&nbsp;</Td>
</Tr>
<Tr>
 <Td ColSpan=2>

<Table Border=0 CellSpacing=0 CellPadding=0>
 <Tr>
  <Td BackGround=../Оболочка/images/bg09.gif Width=458 Height=100 Valign=Bottom>
   <P Class=co>Copyright &copy; БГУИР, Кафедра Систем управления, 2017<Br>
   <Img Src=../Оболочка/images/raspor.gif Width=1 Height=8></P></Td>
  <Td BackGround=../Оболочка/images/bg10.gif Width=159 Height=100>
   <A Href=#Top onMouseOver="mOver(6)" onMouseOut="mOut(6)"><Img Src=../Оболочка/images/06a.gif Width=159 Height=46 Border=0 Alt="К началу документа" name="link6"></A><Br>
   <A Href=!zadanie.html onMouseOver="mOver(7)" onMouseOut="mOut(7)"><Img Src=../Оболочка/images/07a.gif Width=159 Height=54 Border=0 Alt="К первой странице" name="link7"></A></Td>
 </Tr>
</Table>

 </Td>
</Tr>
</Table>

</Body>
</HTML>